from scheduler import Scheduler



if __name__ == '__main__':
    open('myfile.json', 'w').close()
    scheduler = Scheduler(pool_size=3)
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.schedule(start_at="12:00")
    scheduler.run()
    # scheduler.schedule(print_job)
    # sleep(1)
    # scheduler.schedule(print_job)
    # sleep(2)
    # scheduler.schedule(print_job)
    # sleep(3)
    # scheduler.schedule(print_job)
    # scheduler.schedule(print_job)
    # scheduler.schedule(print_job)
